[graph]
exclude-unpublished = true

[advisories]
unmaintained = "none"
ignore = []

[licenses]
confidence-threshold = 1.0
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
    "BSL-1.0",
    "MPL-2.0",
]

[bans]
multiple-versions = "deny"
highlight = "all"
skip-tree = [
    { name = "windows-sys" },
    { name = "getrandom" },
    { name = "r-efi" },
    { name = "rand" },
    { name = "rand_core" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = []
