on:
  pull_request:
    types: [ opened ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.10.1
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Rust
        run: rustup update stable && rustup default stable
      - uses: actions/cache@v5
        with:
          path: ${{ runner.tool_cache }}/cargo-vet
          key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
      - name: Add the tool cache directory to the search path
        run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
      - name: Ensure that the tool cache is populated with the cargo-vet binary
        run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{
          env.CARGO_VET_VERSION }} cargo-vet

      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Cargo.lock
        run: cargo update

      - name: Regenerate cargo vet exemptions
        run: cargo vet regenerate exemptions

      - name: Commit cargo-vet changes
        run: |
          git add supply-chain/*
          git commit -m "vet: update cargo vet exemptions" || echo "No changes to commit"

      - name: Update CHANGELOG
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # Format: - deps(scope): description (#PR_NUMBER)
          CHANGELOG_ENTRY="- $PR_TITLE (#$PR_NUMBER)"

          # Insert entry below [Unreleased]
          sed -i '/\[Unreleased\]/a\'"$CHANGELOG_ENTRY" CHANGELOG.md

      - name: Commit CHANGELOG changes
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG for PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"

      - name: Push commits
        run: git push origin HEAD:${{ github.event.pull_request.head.ref }}
